[package]
name = "rust-os"
version = "0.1.0"
authors = ["chrisando <chrisep8@gmail.com>"]
edition = "2018"

[dependencies]
bootloader_precompiled = "0.3.0"

[package.metadata.bootimage]
default-target = "x86_64-rust_os.json"